# Generated by Django 3.2.13 on 2022-05-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sparkuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
