# Generated by Django 3.2.13 on 2022-05-11 17:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationCommerciale',
            fields=[
                ('configurationCommercialeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationGroupe',
            fields=[
                ('configurationGroupeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationProfil',
            fields=[
                ('configurationProfilID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationUI',
            fields=[
                ('configurationUI_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('SouscriptionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='groupeDeCommunication',
        ),
        migrations.AddField(
            model_name='article',
            name='auteur_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SparkApp.auteur'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='configurationCommerciale_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SparkApp.configurationcommerciale'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='configurationGroupe_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SparkApp.configurationgroupe'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='configurationProfil_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SparkApp.configurationprofil'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='configurationUI_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='SparkApp.configurationui'),
        ),
    ]
