# Generated by Django 3.2.8 on 2021-10-27 01:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_indic', models.CharField(max_length=255)),
                ('no_rue', models.IntegerField()),
                ('nom_rue', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CentreInteret',
            fields=[
                ('ID', models.UUIDField(default='8a3a1fa7-bf9e-463c-9a11-6c5de3901978', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('ID', models.UUIDField(default='24544f1f-420b-435b-91d9-46df73d80a9d', primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=450)),
                ('duree', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('ID', models.UUIDField(default='1deeb35f-1a3d-45f5-b196-48fecc6120a9', primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=450)),
                ('duree', models.DurationField()),
                ('IDchapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkApp.chapitre')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('ID', models.UUIDField(default='1d73a3af-d1be-4086-a891-a67083b01ec9', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('ID', models.UUIDField(default='3dafafd2-e0ab-4ecb-8ce9-df3b0b56926d', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('ID', models.UUIDField(default='0b17f8a7-038f-46c2-ac29-f48be9836b83', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('ID', models.UUIDField(default='6cabde83-e7c0-4a48-ae2f-e16c77059d28', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('ID', models.UUIDField(default='2720662f-8b4e-4c1c-8ffb-e86ddebcb6b3', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilCommercialSpark',
            fields=[
                ('ID', models.UUIDField(default='8990591d-dd76-43b5-8bb6-6c5a23741b05', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('ID', models.UUIDField(default='08843b84-3f48-4714-9dd3-5dceda9d49f9', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('ID', models.UUIDField(default='f2e52d5e-4cfd-483d-82ca-8b2ad306ed18', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('ID', models.UUIDField(default='0172a463-991f-4d90-aace-deb8f7bfb6bb', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=255)),
                ('type_de_numero', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='PhotoFileName',
            new_name='PhotoProfilFileName',
        ),
        migrations.AlterField(
            model_name='authentification',
            name='userId',
            field=models.UUIDField(default='44411d2b-908b-4a0a-9f93-77e84add9a72', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ProfilId',
            field=models.UUIDField(default='6119e678-4000-4288-9cf4-e95f273aabf9', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProfilDetailPersonne',
            fields=[
                ('ID', models.UUIDField(default='19e83b9b-591a-4d2d-8e4c-11b84e01f4c3', primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('sitewebPersonnel', models.URLField(blank=True)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkApp.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('ID', models.UUIDField(default='a4552cfc-b24e-4146-8a9e-15de16ca1730', primary_key=True, serialize=False)),
                ('ID_profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeDeCommunication',
            fields=[
                ('ID', models.UUIDField(default='2d635015-88e6-4a84-a973-c550927832f5', primary_key=True, serialize=False)),
                ('Profil_relie_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('ID', models.UUIDField(default='aad95ff6-2fdd-419c-b9bf-b5755056cb31', primary_key=True, serialize=False)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkApp.cour')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('ID', models.UUIDField(default='8acce160-3032-4553-a0ee-d6a9466447a7', primary_key=True, serialize=False)),
                ('groupeDeCommunication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkApp.groupedecommunication')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('ID', models.UUIDField(default='722eb0d4-ed1a-4221-95c8-5b76b8f9dddf', primary_key=True, serialize=False)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SparkApp.adresse')),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='club_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.club'),
        ),
        migrations.AddField(
            model_name='profil',
            name='configuration_FK_ID',
            field=models.ForeignKey(default='9f7a6ede-31d1-41d5-992a-b367738e41fc', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.configuration'),
        ),
        migrations.AddField(
            model_name='profil',
            name='ecole_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.ecole'),
        ),
        migrations.AddField(
            model_name='profil',
            name='equipe_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.equipe'),
        ),
        migrations.AddField(
            model_name='profil',
            name='groupe_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.groupe'),
        ),
        migrations.AddField(
            model_name='profil',
            name='invitation_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.invitations'),
        ),
        migrations.AddField(
            model_name='profil',
            name='magasin_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.magasin'),
        ),
        migrations.AddField(
            model_name='profil',
            name='media_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.media'),
        ),
        migrations.AddField(
            model_name='profil',
            name='profilCommercialSpark_FK_ID',
            field=models.ForeignKey(default='6a1bf3ec-07ac-4213-ba97-40d890aafdd3', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profilcommercialspark'),
        ),
        migrations.AddField(
            model_name='profil',
            name='profilDetailPersonne_FK_ID',
            field=models.ForeignKey(default='f1e366da-b16d-42c5-bb0e-36345415258c', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profildetailpersonne'),
        ),
        migrations.AddField(
            model_name='profil',
            name='publications_FK_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.publications'),
        ),
        migrations.AddField(
            model_name='profil',
            name='relation_FK_ID',
            field=models.ForeignKey(default='483bb685-d7cb-4e02-b198-0706d67d5dec', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.relation', unique=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='sport_FK_tID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SparkApp.sport'),
        ),
    ]
