# Generated by Django 3.2.8 on 2022-04-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0002_auto_20211026_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentification',
            name='userId',
            field=models.UUIDField(default='5cec157d-f39c-4683-b79d-24ebe89c65ca', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='centreinteret',
            name='ID',
            field=models.UUIDField(default='22ccf8ff-e845-453f-a262-0c8eb7275412', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='ID',
            field=models.UUIDField(default='6ee4cbd4-ecae-4099-ac63-6fe854e00857', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='ID',
            field=models.UUIDField(default='9aabb10c-9614-4338-acbf-f84f27d44afc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ID',
            field=models.UUIDField(default='c6c774ae-44c9-4344-b10b-a958f30b1576', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cour',
            name='ID',
            field=models.UUIDField(default='cadab0d4-1eea-4bd5-a5e3-2558c973fb77', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='ID',
            field=models.UUIDField(default='7128016f-c146-46df-807f-561901a3021a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='ID',
            field=models.UUIDField(default='b728a797-da80-4332-95c9-17e4b0692968', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='ID',
            field=models.UUIDField(default='54315ad9-e16e-4e0d-81af-16afb55b5d6b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='ID',
            field=models.UUIDField(default='af9d9bdb-f691-4320-a5b1-00c07ead2ff3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupedecommunication',
            name='ID',
            field=models.UUIDField(default='33e219a9-9585-4e35-92d6-55d9a71f5fbe', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='ID',
            field=models.UUIDField(default='2e5e2a71-1ef1-439e-b441-11eeea9a66e0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='ID',
            field=models.UUIDField(default='ae87d664-a622-4ece-b7c1-f348550ef2cc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='ID',
            field=models.UUIDField(default='71c6f298-647b-4e9c-8be0-b8b9a1249754', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ProfilId',
            field=models.UUIDField(default='b3c86547-0786-4462-b217-e325232bff54', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='configuration_FK_ID',
            field=models.ForeignKey(default='60b92a34-ffe1-4409-b5a2-eb20751568db', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.configuration'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilCommercialSpark_FK_ID',
            field=models.ForeignKey(default='c461d878-281a-4ab7-9d64-5869b5a2117a', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profilcommercialspark'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilDetailPersonne_FK_ID',
            field=models.ForeignKey(default='aa4f3378-d983-4191-9e93-854acc5db81e', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profildetailpersonne'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='relation_FK_ID',
            field=models.ForeignKey(default='d4868014-1e3e-48f5-ab82-4aad8c93d517', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.relation', unique=True),
        ),
        migrations.AlterField(
            model_name='profilcommercialspark',
            name='ID',
            field=models.UUIDField(default='8ab78fa4-6a03-457f-a630-42dd0befbac6', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profildetailpersonne',
            name='ID',
            field=models.UUIDField(default='9f04b207-7aae-4b38-ae0f-225bd143ee0d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='eb1fe9e3-be64-47e7-a403-a981949428b4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='ID',
            field=models.UUIDField(default='84840c03-8439-440d-8f21-c911abbcbc4e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='ID',
            field=models.UUIDField(default='bec1004a-3c22-4145-b3bc-05c77354432d', primary_key=True, serialize=False),
        ),
    ]
