# Generated by Django 3.2.13 on 2022-05-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0002_auto_20220525_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='sparkuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
