# Generated by Django 3.2.13 on 2022-05-11 19:07

import SparkApp.modelsBo.ModelsUtilitaires.TransactionClass
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0002_auto_20220511_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_Status', models.CharField(choices=[(SparkApp.modelsBo.ModelsUtilitaires.TransactionClass.StatusSubClass['RS'], 'Request sent'), (SparkApp.modelsBo.ModelsUtilitaires.TransactionClass.StatusSubClass['P'], 'Pending'), (SparkApp.modelsBo.ModelsUtilitaires.TransactionClass.StatusSubClass['Err'], 'Error'), (SparkApp.modelsBo.ModelsUtilitaires.TransactionClass.StatusSubClass['C'], 'Completed'), (SparkApp.modelsBo.ModelsUtilitaires.TransactionClass.StatusSubClass['Can'], 'Cancelled')], max_length=4)),
            ],
        ),
    ]
