# Generated by Django 3.2.8 on 2022-04-18 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0003_auto_20220418_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentification',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='centreinteret',
            name='ID',
            field=models.UUIDField(default='8c78ecce-6dfe-499a-9a07-cbadbda43fa7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='ID',
            field=models.UUIDField(default='c079ea1a-7106-408b-b8c5-49375c67ed40', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='ID',
            field=models.UUIDField(default='f78178a1-d2e3-44f5-8a2f-d67233ed85a2', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ID',
            field=models.UUIDField(default='1b7f2d77-4f0b-41a9-84ff-8df06430d59b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cour',
            name='ID',
            field=models.UUIDField(default='b74b6b89-fe1c-4de4-8ccd-5d151a837402', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='ID',
            field=models.UUIDField(default='c0a9e785-dc41-4459-887e-952ae0447c2f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='ID',
            field=models.UUIDField(default='601b3907-3587-4ece-917e-7ee72784ca3d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='ID',
            field=models.UUIDField(default='b37390ec-f174-40b0-a109-49638a22dcb5', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='ID',
            field=models.UUIDField(default='d8d4a77c-2b37-4813-8ee0-cb6449c9522d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupedecommunication',
            name='ID',
            field=models.UUIDField(default='83e85a3c-59c8-4526-a538-e84c36ebdb7f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='ID',
            field=models.UUIDField(default='33b5a649-5821-4fb6-bd05-161cb01cc2da', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='ID',
            field=models.UUIDField(default='50f1d64b-0b63-4e25-aa94-e9abe7e526f7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='ID',
            field=models.UUIDField(default='c57a10ad-ed4e-442b-9c01-3dedc6b4c3ff', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ProfilId',
            field=models.UUIDField(default='bf545649-16d0-4fa8-bbb7-b118b6b2049a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='configuration_FK_ID',
            field=models.ForeignKey(default='29ed83d3-2e88-4be8-aa98-9852fe2ad7e0', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.configuration'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilCommercialSpark_FK_ID',
            field=models.ForeignKey(default='30ec9b26-1c8e-457d-9896-be853be7a708', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profilcommercialspark'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilDetailPersonne_FK_ID',
            field=models.ForeignKey(default='e72b60af-7a4b-495d-aa64-529e96682d41', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profildetailpersonne'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='relation_FK_ID',
            field=models.ForeignKey(default='e05f1628-d4fd-448a-8de4-9742f93e3698', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.relation', unique=True),
        ),
        migrations.AlterField(
            model_name='profilcommercialspark',
            name='ID',
            field=models.UUIDField(default='0f15282e-7784-41b1-a2e0-30233eb23d4e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profildetailpersonne',
            name='ID',
            field=models.UUIDField(default='ec660064-2844-4540-b444-8ce882c685cc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='f1bc7584-6d1c-4ae1-9761-c169b78b84b3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='ID',
            field=models.UUIDField(default='fcc65ed8-ae6a-4d0a-bb5e-886681e82f87', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='ID',
            field=models.UUIDField(default='982cc315-c1ff-4602-9c6a-b7afe78c203a', primary_key=True, serialize=False),
        ),
    ]
