# Generated by Django 3.2.8 on 2022-04-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0004_auto_20220418_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreinteret',
            name='ID',
            field=models.UUIDField(default='3cc783dc-d651-4823-b42d-3b2e8d80667a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='ID',
            field=models.UUIDField(default='6d995d65-8037-4ee0-8eb8-6862651aecc3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='ID',
            field=models.UUIDField(default='beb9302d-a256-47ca-b212-b328decb3e2a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='ID',
            field=models.UUIDField(default='eedd6ad6-8172-4e9d-a312-4d23da608eec', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cour',
            name='ID',
            field=models.UUIDField(default='2bda3aad-84b2-44d8-bbf9-e831a82d6acd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='ID',
            field=models.UUIDField(default='ce8e10a4-ecc2-4318-90e3-0b4942cc475f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='ID',
            field=models.UUIDField(default='fee44edf-647c-400b-bf3c-580f46aa4d43', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='ID',
            field=models.UUIDField(default='5fdc2790-de0e-4ef2-8cfa-4254da7e6359', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='ID',
            field=models.UUIDField(default='5b47de29-b851-4306-8d5c-82eed641666d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupedecommunication',
            name='ID',
            field=models.UUIDField(default='7b595f81-407f-4fcb-9de2-b25e2360c8fd', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitations',
            name='ID',
            field=models.UUIDField(default='2b0f018a-f14f-4562-b08a-94a7de1da021', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='ID',
            field=models.UUIDField(default='317ed983-dcc9-479f-899c-73f0e649fb8b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='ID',
            field=models.UUIDField(default='d15525e9-a103-42a8-8a7a-96a6dd480940', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='ProfilId',
            field=models.UUIDField(default='2c91f7e7-a52d-4485-81d7-c134a55aabb4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profil',
            name='configuration_FK_ID',
            field=models.ForeignKey(default='22d3e9ba-469d-44d2-8517-f4e3f450e3a2', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.configuration'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilCommercialSpark_FK_ID',
            field=models.ForeignKey(default='b6ba6fb8-7892-42d3-9bc3-63406587cfaa', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profilcommercialspark'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilDetailPersonne_FK_ID',
            field=models.ForeignKey(default='e2a192a9-c724-4b86-af1f-a5ad5d6023d1', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.profildetailpersonne'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='relation_FK_ID',
            field=models.ForeignKey(default='beb2e04e-f904-4253-8fe5-e03dcbbebc3f', on_delete=django.db.models.deletion.CASCADE, to='SparkApp.relation', unique=True),
        ),
        migrations.AlterField(
            model_name='profilcommercialspark',
            name='ID',
            field=models.UUIDField(default='a60be485-6dbb-4226-a193-7acd171c2176', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profildetailpersonne',
            name='ID',
            field=models.UUIDField(default='e1d7a73d-b8d0-46ee-92ba-4d5cf4da7673', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='b236b488-0e45-4b90-9d4c-4a309fa934e0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='ID',
            field=models.UUIDField(default='a405939a-bea2-427c-8cf0-21daf0ebd87c', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='ID',
            field=models.UUIDField(default='f4428a49-8a67-469b-b2c5-98219a1314c7', primary_key=True, serialize=False),
        ),
    ]
