# Generated by Django 3.2.13 on 2022-05-13 19:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0006_administrateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
