# Generated by Django 3.2.13 on 2022-05-10 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0006_auto_20220419_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('AuteurId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='ecole',
            name='ID',
        ),
        migrations.AddField(
            model_name='ecole',
            name='EcoleID',
            field=models.UUIDField(default='ef37383b-a768-4a84-9dd0-259bccaab2af', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='AlbumPhotoID',
            field=models.UUIDField(default='e61e7af0-51e5-4789-a43d-072195ed8d4f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupID',
            field=models.UUIDField(default='9b848a4d-d6d2-402c-a432-ede142a184e4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitationID',
            field=models.UUIDField(default='86bb05f2-ca38-4db6-bf88-545ceeb8ab60', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='videoID',
            field=models.UUIDField(default='08902dd3-cbc0-4208-addb-23bc181719a1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='1fcbccc9-27f3-4eb8-87a0-19f4faad4f46', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='publiciteID',
            field=models.UUIDField(default='68665041-7304-4aa8-a72c-0a8dc12a1fc0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relationID',
            field=models.UUIDField(default='4064a269-eafa-4fa7-89ab-b978684e904f', primary_key=True, serialize=False),
        ),
    ]
