# Generated by Django 3.2.13 on 2022-05-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0007_auto_20220509_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='AlbumPhotoID',
            field=models.UUIDField(default='7ef80e96-c0bf-4236-81f8-70e06ed9dd2d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='EcoleID',
            field=models.UUIDField(default='1ed2d32b-1fdd-49e6-804b-452f56c271aa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupID',
            field=models.UUIDField(default='e717d463-d32c-4c00-b882-5bcdba300d6e', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitationID',
            field=models.UUIDField(default='c92f2f7b-de62-496f-afe5-795f756c5ee4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='videoID',
            field=models.UUIDField(default='dc113e36-cbcb-4a40-a650-e73fb73042c0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='07524673-720e-4921-8aed-fc7afb491525', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='publiciteID',
            field=models.UUIDField(default='30fefbd5-9275-41f2-b251-7d25ab06e1c4', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relationID',
            field=models.UUIDField(default='07eb6ebc-61de-4bf1-a008-fe7b578530e1', primary_key=True, serialize=False),
        ),
    ]
