# Generated by Django 3.2.13 on 2022-05-17 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produitId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField(default=0)),
            ],
        ),
    ]
