# Generated by Django 3.2.13 on 2022-05-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0008_auto_20220509_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='AlbumPhotoID',
            field=models.UUIDField(default='4a6eee9d-fb8c-463b-a907-2c20f03e09d8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='EcoleID',
            field=models.UUIDField(default='d08ac8cc-8c59-42cd-b780-10d69505664b', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupID',
            field=models.UUIDField(default='d1452dda-11fc-4071-b910-95ac3ef2a0be', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitationID',
            field=models.UUIDField(default='6fda06fc-2c1f-4a34-851b-8da371a241aa', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='videoID',
            field=models.UUIDField(default='9dbaeb33-f64f-44c0-b062-12f9042c2890', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='79be30dd-8de1-4bf2-8895-9126bda13c1a', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='publiciteID',
            field=models.UUIDField(default='0c4434b6-7329-47bc-8bb5-45027b085fd7', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relationID',
            field=models.UUIDField(default='9e9a98ce-1c67-433e-9b1d-7f23f75c4437', primary_key=True, serialize=False),
        ),
    ]
