# Generated by Django 3.2.13 on 2022-05-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0009_sparkuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparkuser',
            old_name='motdepasse',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='sparkuser',
            old_name='user',
            new_name='user_Id',
        ),
        migrations.RenameField(
            model_name='sparkuser',
            old_name='name',
            new_name='username',
        ),
    ]
