# Generated by Django 3.2.13 on 2022-05-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0009_auto_20220509_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumphoto',
            name='AlbumPhotoID',
            field=models.UUIDField(default='977f835c-d968-441e-ac95-c0edd0ee56a3', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='EcoleID',
            field=models.UUIDField(default='6737c55d-d050-4abf-bbfd-63789b4e864d', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupID',
            field=models.UUIDField(default='7f293c0f-47fc-4704-833e-42a28b22d4a0', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitationID',
            field=models.UUIDField(default='15d602d8-53f3-49e3-ad33-9e271d2e03c8', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediavideo',
            name='videoID',
            field=models.UUIDField(default='cec1b4da-935a-4bc1-8e0a-049326ace237', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publications',
            name='ID',
            field=models.UUIDField(default='48813fbb-8ed7-4985-89a3-f3770bffa4fc', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='publiciteID',
            field=models.UUIDField(default='c1f69af1-8daa-4d63-a4f0-92ee1b66f15f', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relation',
            name='relationID',
            field=models.UUIDField(default='b10ad28a-f30d-4282-addf-be474b096d8e', primary_key=True, serialize=False),
        ),
    ]
