# Generated by Django 3.2.13 on 2022-05-23 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SparkApp', '0010_auto_20220522_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparkuser',
            old_name='user_Id',
            new_name='user',
        ),
    ]
